# Generated by Django 4.0 on 2021-12-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='post',
            field=models.BooleanField(default=False),
        ),
    ]
